### ISSUE TITLE
Discuss Eugene 

### ISSUE THREAD

**Issue by jeromekelleher** [sgkit-dev/vcf-zarr-publication#7]
Uses zarr, xarray and dask. Lots of commonality with sgkit.

Have you seen this @hammer ?

https://www.nature.com/articles/s43588-023-00544-w

**Comment by hammer** [comment]
New to me! The [Twitter thread](https://twitter.com/KlieAdam/status/1725211400157741106) from the first author was helpful for some context. It definitely seems to share our philosophy with a focus on DNA and RNA sequence data rather than variants. Some upstream projects include [SeqPro](https://github.com/ML4GLand/SeqPro) and [SeqData](https://github.com/ML4GLand/SeqData).

The machine learning workflow actually reminds me of our internal framework at Related Sciences built on Xarray that Eric recently made open source, https://github.com/related-sciences/xrml...

**Comment by hammer** [comment]
Amusingly this paper showed up in my Semantic Scholar recommended reads today, clearly the universe wants me to read it more closely.
